#!/usr/bin/env php
<?php
/**
 * Part of the Joomla Command Line Package
 *
 * @copyright  Copyright (C) 2015 - 2016 Open Source Matters, Inc. All rights reserved.
 * @license    GNU General Public License version 2 or later; see LICENSE
 */

namespace Joomla\Cli;

ini_set('date.timezone', 'UTC');

$loaded = false;

foreach ([__DIR__ . '/../../autoload.php', __DIR__ . '/vendor/autoload.php', __DIR__ . '/libraries/vendor/autoload.php'] as $file)
{
	if (file_exists($file))
	{
		require $file;
		$loaded = true;
		break;
	}
}

if (!$loaded)
{
	die(
		'You need to set up the project dependencies using the following commands:' . PHP_EOL .
		'wget http://getcomposer.org/composer.phar' . PHP_EOL .
		'php composer.phar install' . PHP_EOL
	);
}

require_once __DIR__ . '/init.php';

$console = new \Joomla\Cli\Application(initContainer());
$console->run();
